[project]
name = "discord-notifier"
version = "0.1.0"
description = "discrod notifier"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow>=12.0.0",
    "requests>=2.32.5",
    "selenium>=4.38.0",
]

[dependency-groups]
dev = [
    "black>=25.9.0",
]
