name: TenkiJP

on:
  workflow_dispatch:
  schedule:
    - cron: "00 22 * * *" # JST 07:00
    - cron: "00 6 * * *" # JST 15:00

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.9.5"
          enable-cache: true
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: uv Sync
        run: uv sync --locked --all-extras --dev
      - name: Run
        run: |
          uv run python main.py \
            --mode tenki-jp \
            --discord-webhook-url ${{ secrets.DISCORD_WEBHOOK_URL }} \
            --dry-run false
