name: TenkiJP

on:
  workflow_dispatch:
  schedule:
    - cron: "00 22 * * *" # JST 07:00
    - cron: "00 6 * * *" # JST 15:00

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Python packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"
      - name: Cache ChromeDriver
        uses: actions/cache@v2
        with:
          path: /usr/local/bin/chromedriver
          key: ${{ runner.os }}-chromedriver-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-chromedriver-
      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: '88.0.4324.96'
          chromeapp: chrome
      - name: Install Japanese Font
        run: sudo apt-get install -y fonts-noto
      - name: Cache pipenv
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-kyes: |
            ${{ runner.os }}-pipenv-
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: pipenv install
  run:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: |
          pipenv run python main.py \
            --mode tenki-jp \
            --discord-webhook-url ${{ secrets.DISCORD_WEBHOOK_URL }} \
            --dry-run false
